repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
    - id: terraform_tflint
    - id: terraform_validate
    - id: terraform_fmt
    - id: terraform_tfsec
    - id: terrascan
    - id: terraform_checkov
      args:
        - --args=--quiet
    - id: terraform_docs
      verbose: true
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.9.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
